### PR TITLE
add nominatim geocoder

### PR DESCRIPTION
**Pull request by nycex**
This patch adds a Geocoder for use with the OSS build flavour which requires no API key. Nominatim is the geocoder from the OpenStreetMap project.

### CODE REVIEW

**Comment by growse** [comment]
Thanks for this. Implementation makes sense.

One q: the nominatim ToS (https://operations.osmfoundation.org/policies/nominatim/) request that clients make no more than 1 request per second, and that this limit "apply per website/application: the sum of traffic by all your users should not exceed the limits". My expectation is that it wouldn't take too many app users to be in move mode before we start to run into this limit, and while the current install base isn't huge, it's not small either (000s). That said, it's not going to be the default for the GMS flavour, so I don't have a good feeling of what the usage rates would be.

I guess I'm saying we don't have a good control over what this usage rate is across all users, and I don't want to annoy the people running the service. I would look at hosting our own instance, but this looks expensive (1TB NVMe disk, 64GB RAM etc.)

**Comment by nycex** [comment]
Good point.
Just as a though, there are other instances one of which might be feasible: https://wiki.openstreetmap.org/wiki/Nominatim#Alternatives_.2F_Third-party_providers

**Comment by growse** [comment]
I wonder if they all have a common API format? If they do, then it should be pretty simple to implement a Reverse Geocoder and then just vary the hostname / credentials for different services.

**Comment by nycex** [comment]
I think some of them do, but others are just commercial sites that often have different APIs and and require credentials as it seems.

**Comment by growse** [comment]
Most of these providers seem similar to opencage, in the sense that you can use them for free up to a few thousand requests per day, which should be enough for a single user. Some even give you friendly status codes that let you back off requests when you exceed that. But yes, they do all require some form of API key, which is annoying.

I think there's value in adding more choice on reverse geocoders (some have more specific benefits to different areas), but I don't know if it's right to include support for a free service where we have no way of ensuring that we're meeting their ToS. 

Given that the end-goal is to get a build onto F-droid, which means no Google play services / map services, I do notice that the Google geocoder doesn't depend on any play service dependency - it's just part of `android.location`. I wonder if that means that for an OSS build of OT, we can still ship with the Google reverse geocoder (which doesn't require credentials), but set the default to be "None"? This then at least gives the user the choice of hitting Google, OpenCage or whoever for geocoding, but without defaulting them into anything.

**Comment by growse** [comment]
Going to close in favour of defaulting to a "none" geocoder for the F-Droid / OSS build as per ed69497

**Pull request closed without merging**
