### PR TITLE
Hive

### PR DESCRIPTION
**Pull request by Robert77a691**
V

### CODE REVIEW

**Comment by Robert77a691** [comment]
project/app/dependencies.gradle
project/app/src/main/java/org/owntracks/android/support/GeocoderGoogle.java
project/build.gradle

**Comment by Robert77a691** [comment]
Duplicate of #

**Comment by Robert77a691** [comment]
Dfdd

**Comment by jpmens** [comment]
You have 10 minutes to tell us what you are trying to do before I block you.

**Pull request closed without merging**
