### PR TITLE
Add a menu option to fully close the app

### PR DESCRIPTION
**Pull request by chrgro**
As previous PR, adding a menu option to full close the app and shut down the background service.

Menu option is only visible at the Map screen, as this is the "root" activity that can be closed. 

Did some code refactoring as per previous discussions (accidentally closed that PR when deleting my local branch)

### CODE REVIEW

**Comment by chrgro** [comment]
It visually looks like this: 
image

**Comment by growse** [comment]
Looks good, thanks!

**Comment by chrgro** [comment]
Cheers, thanks for merging!

**Comment by chrgro** [comment]
How often do you publish a new version on the play store? In other words when can I expect this change to go public? :)

**Comment by jpmens** [comment]
We have no fixed schedule. Generally, if something has to be fixed urgently we do it as quickly as possible. Otherwise, when it’s convenient.

It will happen. We cannot say when.

**Pull request merged**
