### PR TITLE
Remote Config #7

### PR DESCRIPTION
**Pull request by massimilianozilio**
Please have a look at the changes and let me know if you have any questions.

### CODE REVIEW

**Comment by massimilianozilio** [comment]
Hi @binarybucks ,
have you had time to review this pullrequest?  Is it still pending?

Max

**Comment by binarybucks** [comment]
I cannot merge it automatically so I'd have to fire up my Android IDE which I don't have access to at the moment.

**Comment by massimilianozilio** [comment]
Ok, I just wanted to let you know that I am back from my trip so if you
have any questions or problems with those changes please let me know.

Max

**Comment by binarybucks** [comment]
I've revieved the code. It looks very good and ready to merge. If you're looking for new things to contribute, could you look into https://github.com/owntracks/android/issues/86?

**Comment by jpmens** [comment]
Welcome back @massimilianozilio ! It would be great if you could look at what's happening in the issue binarybucks mentioned; people are heavily complaining about the lack of reports when app is in background.

**Comment by binarybucks** [comment]
Finally merged manually. Thanks for your contribution and patience.

**Comment by jpmens** [comment]
Thank you both!

**Comment by massimilianozilio** [comment]
No problem.  Now that this has been merged it shouldn't be to hard to
implement Config from Clipboard.  Unfortunately I am currently very busy
but I hope I will restart contributing soon.

Cheers
Max

**Pull request closed without merging**
