### PR TITLE
Updated description for inaccuracy

### PR DESCRIPTION
**Pull request by grisu48**
I've updated the description for the Inaccuracy option for better understanding
Now a user should be able to put in some meaningful values
Commit 6045895

### CODE REVIEW

**Comment by grisu48** [comment]
I've added toast messages in the main activity and in the preferences, so that the user gets a notification, if no connection could be established.

**Comment by binarybucks** [comment]
Good work, thank you. Please submit a separate pull request for the toast. While you're at it, I suggest to replace all the listeners and callbacks with the EndpoinStateChanged EventBus message.

**Comment by grisu48** [comment]
Thanks for the quick reply. I'll have a look at it on the weekend. Greetings :+1:

**Comment by binarybucks** [comment]
Description updated in version 2.x. 
Status display will be solved differently.

**Pull request closed without merging**
