### PR TITLE
Client .p12 Certificate Import

### PR DESCRIPTION
**Pull request by bpillatsch**
This will give users the ability to send client certificates in addition to validating the server signed cert. A much more secure method of remote WAN connection to MQTT broker instead of relying on insecure user/password strings.

Implemented kmf for client .p12 (without password) importing. Added UI fields in keeping with key/string conventions. Reworked sslcontext init to streamline CA or Client Cert, CA + Client Cert, options.

If either field is empty their values will be initialized to null in the case of client cert or initialized off the system keystore in the case of CA.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by binarybucks** [comment]
Hi, 

thanks for your awesome work, this pull request is really well done and provides a great new feature. 
We are currently preparing some really big things for the launch of iOS app v.8 and Android v.0.5 that require some more involved internal changes in the apps. 

Judging from the code I will not be able to merge your code manually due to my recent changes but I promise to merge it in manually and ship it with 0.5. 

One remark though. Please do not change existing preferences keys in future releases as those are also used for exported configs. When they're changed, the setting cannot be imported from old configs. 
Currently it's ok as I was shuffling keys around from 0.4 anyway

**Comment by jpmens** [comment]
@bpillatsch I'd like to add you to a list of contributors I'm creating for the new documentation. If you're willing to send me (jpmens@gmail.com) your name, I'll gladly do so!

**Comment by bpillatsch** [comment]
Thanks for the feedback @binarybucks, I'm happy to revert those preference keys if it would be of any help.

Are you by chance working on a file selection dialog for these fields? If not would you be interested in that feature? I'd be happy to continue work on that if you have not started and are interested.

**Comment by binarybucks** [comment]
file selection dialog would be grand, please continue ;)

--
Alexander Rust

On 20 Apr 2015, at 15:22, bpillatsch <notifications@github.com> wrote:

Thanks for the feedback @binarybucks <https://github.com/binarybucks>, I'm
happy to revert those preference keys if it would be of any help.

Are you by chance working on a file selection dialog for these fields? If
not would you be interested in that feature? I'd be happy to continue work
on that if you have not started and are interested.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/pull/168#issuecomment-94449681>.

**Comment by jpmens** [comment]
@bpillatsch Thanks for your email, and yes: please continue! :smile:

**Comment by binarybucks** [comment]
@bpillatsch please continue using your branch and attach your code to this pull request. I'll merge the changes manually to my local branch.

**Comment by binarybucks** [comment]
I've just merged your changes into the master branch, thank you very much for your contribution. 
It will be available with the next release when used with your own broker.

**Pull request closed without merging**
