### PR TITLE
Modify reportLocation to cause a live location lookup.

### PR DESCRIPTION
**Pull request by grheard**
This change is in relation to issue 660. It modifies the reportLocation command to cause a live location update. The new logic path makes use of the existing publishLocationMessage method and as such honors the logic surrounding privacy.

Side note, this is my first time working with Android code. I look forward to hearing your comments and suggestions for improvement.

### CODE REVIEW

**Comment by binarybucks** [comment]
Thank you for this PR. Nicely done with bonus points for reusing the publichLocationMessage code path. 

I've to think about the way the location request is started. I'm not sure that saving the service as an instance variable of the `LocationProcessor` is a good idea.

**Comment by grheard** [comment]
> I'm not sure that saving the service as an instance variable of the `LocationProcessor` is a good idea.

Admittedly, this is where my knowledge of Android/Java is lacking. I couldn't find a good way for MessageProcessor to access the BackgroundService directly.

**Comment by binarybucks** [comment]
Thank you for your contribution. I've slightly modified the communication between `LocationProcessor` and `BackgroundService`. It works the same but is a bit more abstracted away from the `LocationRepo`. 
It's probably equally wrong implementation wise but I too cannot think about a better way to do it. 
I also added a timeout parameter to the request to prevent it from hanging with high power use when no fix can be acquired. See all changes in cd6a42d44b19d694d6d5fc77d6fa07bdd269fedc. 
The code is merged into the master branch and will be shipped with the next release.

**Comment by grheard** [comment]
Awesome, thanks!

**Pull request merged**
