### PR TITLE
Use of better default subTopic

### PR DESCRIPTION
**Pull request by nycex**
Fixes https://github.com/owntracks/owntracks/issues/22

### CODE REVIEW

**Comment by nycex** [comment]
That's a reasonable why I linked the issue, because it is already explained well there.

**Comment by nycex** [comment]
But in a nutshell: 
Like the booklet already mentions, you have to use this value if you want waypoints to be published so i think it is a better default.

**Comment by binarybucks** [comment]
You don’t have to change subTopic to get waypoints published from the device

**Comment by nycex** [comment]
That's what says the booklet:
"Subscribers to the broker (our apps and any other program) can avoid getting waypoints by subscribing to, say, owntracks/+/+; also broker ACLs can prohibit access to owntracks/+/+/waypoint for particular users if so desired. Conversely, all messages published by the apps (location and waypoint) are available with a subscription to owntracks/#."

**Comment by jpmens** [comment]
All our users have so far not had a problem with this, nor have we. I am now closing this. Thank you for your contribution but we will not take it at this time.

**Pull request closed without merging**
