### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by notgood**
Add warning to README, app is currently broken when used in "GPS only" mode, other Android location modes are compromising users privacy.

### CODE REVIEW

**Comment by growse** [comment]
If there's a bug, raise it as an issue please.

**Comment by notgood** [comment]
... or perhaps one could read the pull request contents before closing.

Bug reported is linked there, reported 5 months ago and ignored since.

**Comment by jpmens** [comment]
#1410

**Comment by growse** [comment]
> ... or perhaps one could read the pull request contents before closing.
> 
> Bug reported is linked there, reported 5 months ago and ignored since.

I did read the pull request. I'm not duplicating the bug tracker in the readme.

And with the pissy attitude about a bug being "ignored" (it hasn't been, by the way), I'm even less inclined to spend any time thinking about it now than I was before. Frankly, I've got more important issues to deal with.

**Pull request closed without merging**
