### PR TITLE
Added missing delete regions code 

### PR DESCRIPTION
**Pull request by wir3z**
Removes regions returned with invalid coordinates to match the iOS app and documentation.

### CODE REVIEW

**Comment by wir3z** [comment]
Great idea.  Pushed a patch to log a warning for each skipped waypoint.

**Review by growse — APPROVED** [review]

**Comment by growse** [comment]
Could you re-base this onto master, rather than the 2.4 branch?

**Comment by wir3z** [comment]
> Could you re-base this onto master, rather than the 2.4 branch?

You bet.  I'll get a PR for that.

**Comment by growse** [comment]
Fixed in #1597

**Pull request closed without merging**
