### PR TITLE
Pull master branch to fork

### PR DESCRIPTION
**Pull request by knr1**

### CODE REVIEW

**Comment by knr1** [comment]
Try to update fork

**Comment by binarybucks** [comment]
what exactly are you trying to achieve?

--
Alexander Rust

On 30 Apr 2015, at 08:42, reto <notifications@github.com> wrote:

Closed #181 <https://github.com/owntracks/android/pull/181>.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/pull/181#event-293726281>.

**Comment by knr1** [comment]
Excuse me, something went terribly wrong!
I just wanted to do the opposite!
I wanted to update from your master into my fork.
It seems as if I just provoked the opposite!

Sorry! Still a beginner in GitHub... Just followed the wrong tutorial it seems:
http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/

How can I undo that?

**Comment by jpmens** [comment]
You don't have to do anything. This PR is closed.

**Comment by binarybucks** [comment]
no worries nothing happened, I'll close the pull request later.

--
Alexander Rust

On 30 Apr 2015, at 08:45, reto <notifications@github.com> wrote:

Excuse me, something went terribly wrong!
I just wanted to do the opposite!
I wanted to update from your master into my fork.
It seems as if I just provoked the opposite!

Sorry! Still a beginner in GitHub... Just followed the wrong tutorial it
seems:
http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/

How can I undo that?

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/pull/181#issuecomment-97679998>.

**Comment by jpmens** [comment]
@knr1 For your information: when you submit a pull-request nothing much happens: the receiver of the PR decides whether (s)he wants to merge it or not. So, while we didn't really understand what you were doing, you didn't cause any damage. :)

**Comment by knr1** [comment]
Oh, good to know! Thank you for the explanations!
So I will exercise the updating of a fork and then will come back again and if all goes well you will not recognize this specific action of mine any-more :-)

Oh, b.t.w: Great project! We will try to bring in a format preserving encryption (fpe) of the data, so one could use any public mqtt-broker without having to loose privacy... As the encryption is format preserving, OwnTracks would still work even if it did not know about the encrypted data (or the encryption key used per provider)... it just would display valid but wrong information.
But we just started and will try to disturb you only when we have finished our implementation... Meanwhile we just want to keep up to date with the master repository...

**Pull request closed without merging**
