### PR TITLE
- update AltBeacon lib for bugfix 'No Monitoring information after ki…

### PR DESCRIPTION
**Pull request by rdehuyss**
- update AltBeacon lib for bugfix 'No Monitoring information after killing an application built with the minify mode'
- Set Waypoint in red when triggered by IBeacon

### CODE REVIEW

**Comment by binarybucks** [comment]
What was the reason to change the Paho version back to 1.1.0?

**Comment by rdehuyss** [comment]
The version mentioned in build.gradle was not available in JCenter, so I did not know on how to get it... are there any special bugfixes in it?

Here is the link for JCenter: https://jcenter.bintray.com/org/eclipse/paho/org.eclipse.paho.client.mqttv3/

**Comment by binarybucks** [comment]
Yes, 1.1.0 is pretty old and has several websocket related issues. Hence I'm using the snapshot builds directly from the Paho repository. They tend to get swapped out after new daily builds are uploaded so we've to change the dependency every couply of weeks. It probably will be some time until there is a stable 1.1.1 build anywhere. 

I'll fix it and replace it with the current proper build.

**Comment by rdehuyss** [comment]
Ok, I did not know that... hopefully the rest is ok.

There is one thing that I also would be a nice improvement which is the following: if you now add a region which is IBeacon enabled, the BeaconManager is not restarted. Once the ServiceBeacon is instantiated (e.g. after a fresh install), it will not start the BeaconManager if you create a region.
Would that not be solved by Subscribing with the GreenRobot EventBus on the following method?

    public void onEvent(Events.WaypointAdded e) { ... }

I did not add it because there might be a reason for it that I do not know.

Nice readable code by the way! Any interest in unit tests?

**Comment by binarybucks** [comment]
Yes, onEvent is fine, you can look at the ServiceLocator, it uses the same event to reinitialize regions. 

I'm currently looking at the setType call. You're kind of misusing it but it is currently not used anywhere. 
Also, what happens if a leave is missed (e.g. Bluetooth switched off while leaving). It would still show as inside, right? 

Unit tests would be great, but so far there were more important things to fix ;)

**Comment by binarybucks** [comment]
What about dropping `wifiSSID`, and `type` and adding a lastTriggeredState int. This way we could also add the inside/outside feature to location based waypoints. 

In a second step we could then show them on the map with their according state which is an often requested feature.

**Comment by rdehuyss** [comment]
- Since it's not my codebase I was looking for the thing with the least amount of impact, so that is why I used the type which was indeed not used anywhere
- Regarding leaving with bluetooth off AND not having a radius: I think you are right, it would still show as inside. But is that not a strange usecase? One way to solve it, would be to listen for changes on the bluetooth adapter. For me, showing the region in red was just to see whether I configured owntracks correctly for IBeacon support.
- The idea of a lastTriggeredState sounds great - I just don't know how this would work with backwards compatability in the database...

Until the end of this month, I'm quite busy but once February I would be glad to help with these improvements...

**Comment by binarybucks** [comment]
Valid point, you can't get around it once you track state. If you miss a change, the state will be wrong. 

I'll add another DB field for the state once @nma83 sends his widget PR. I don't want him to fix yet another round of merge conflicts :D 
I've to add a db migration function anyway so we don't nuke waypoints on every db change.

**Comment by binarybucks** [comment]
beacon updates were included manually

**Pull request closed without merging**
