### PR TITLE
Freeform mode: configurable ClientId and DeviceTopic

### PR DESCRIPTION
**Pull request by tmylk**
I really like OwnTracks and would like to use it with OpenSensors.io - it is a free backend which is always up and persists my messages. I wasn't sure if I would be able to configure o2s or m2s myself, so decided to stick with Opensensors for persistence.

 The legacy owntrack worked well with them but I had problems with the new version, so I added a compatible mode called Freeform. I tested it with OpenSensors on my Nexus 5.

It can be used with any generic MQTT broker. That way OwnTracks doesn't close the ecosystem to just OwnTracks publich/hosted/private backends!

Freeform mode allows to explicitly define:

- Client ID.  (Old version it is only set when importing JSON properties and thus is always empty. When empty falls back to Android build name.)

- DeviceTopic

Let me know if there is anything that needs to be changed to incorporate it. It will be used as part of our Total Exposure London Pollution app. (You have seen us hacking on it in a Twitter photo a couple of months ago.)

### CODE REVIEW

**Comment by jpmens** [comment]
What is this "compatible mode called freeform"? Am I understanding correctly that this PR is adding a new payload type? If so, we won't take it. JSON is fine as it is and we're not aware of anybody who's had "problems with it". I think it would be good if you describe the "problems" you've had.

**Comment by jpmens** [comment]
We've looked at this a bit more. Thank you for your contribution, but we won't take this. Too much code for doing something which can already be done via config import. We explicitly removed a number of configuration items from the UI recently in both Android and iOS to make the apps simpler to configure.

**Comment by tmylk** [comment]
Thank you for considering this code. Unfortunately I didn't know that  the Import Config feature has been implemented: I couldn't find the Import buttonon my Android screen! I can see the code in ActivityImport.java but there is no button to try it out on my phone. Will it be available to test out soon?

Do I understand correctly that this is how the Import Config should be used when it becomes available:
1) Set mode to  Private.
2) Click the import button to import config in JSON from somewhere

Is this the correct use case?

There are some issues with this approach:
1) No way to view the imported config's ClientId and DeviceTopic in UI.  In the UI it will look as though I am in private mode with a private OwnTracks MQTT backend which is not the case.
2) Need to store my password in clear text.
3) Need to guess somehow that client id and device id are two different things! That wasn't obvious to me.
4) Editing JSON on the phone is a bit tricky.
5) The App will still keep sending TrackerId even though I don't need it.

Having an explicit UI in this pull request will actually make the app easier to configure. Especially for someone who doesn't want to be chained to your OwnTracks MQTT broker backend like Pista.

I was really surprised that the new version of OwnTracks actually has more limited features than the previous one in terms of config. Is it ok if I keep my fork for our ap purposes? Is it ok if I publish it under OwnTracksFreeForm on Google Play Store? I need it to record location for my another app.

Thanks

**Comment by binarybucks** [comment]
Hi, 

you can import a configuration by choosig the OwnTracks app from the Android open dialog. E.g. if you have the .otrc file in your Dropbox or GMail app, click the file and choose to open it with OwnTracks. A dialog will show all config keys and values that will be imported. You can even include the mode to which the config will apply and which will be activated after importing the config, so you don't even need to specify private mode before importing it. 

Regarding your questions: 
1) You said you were confused that deviceID and clientId were different things. Let me say that you were not alone with this. This is *exactly* why we removed it from the interface. The clientId is a MQTT specific thing that normally doesn't need to be set to a specific value and with the MQTT 3.1.1 specification can even be ommited entirely. Regarding the device topic, we had many support requests because people changed it and wondered why their reported locations didn't occur on other devices because they didn't know what they were doing. Thus we opted to remove it in newer versions and make it configurable via config import for advanced users. 

Could you specify a usecase why you need to regularly view the clientId and device topic in the app? I believe it's something you configure once and then forget about it. 

Moreover, private mode refers to using OwnTracks with the infrastructure of your choice. This is explained in great detail in the documentation. This can be private infrastructure or a public third party public infrastructure, so the name **might** me confusing. How would you name the mode then? 

2) The imported config doesn't need to include your password. If you export the config, you can choose to not include any credentials and just export common config values. Alternatively, if you have an existing config, you can edit the file and just remove the parameter. If some config keys are not included in the config, the import of that key is just skipped and the configured value is not changed so no one forces you to export your password in clear text. You can thus just distribute a config without password and meet in a tap-proof room in person do distribute passwords. 

3) This is exactly why you cannot configure it in the interface like explained above. 

4) Why would you need to do that?

5) Yes, and it's also sending **radius**, **tst** and much more that you might not need. We cannot make everything configurable. 

Sorry for the harsh words, but the provided pull request does not make it easier to configure but instead provides an additional mode that is completely redundant and will most probably confuse everyone besides you. 

You are explicitly *not* chained to our backends. You are still free to configure all important parameters. User relevant parameters can be configured the the app while advanced features can be set through the imported config. 

Also, removing options form the visible interface of the app was a conscious decision because there were many features that are seldomly needed because we provide sane defaults and that were configusing for 99% of regular users. 

That being said, you are of course free to maintain your own fork on Github and distribute it to your friends, family and pets as long as it adheres to the EPL license. **However**, do not distribute it to Google Play under the name OwnTracks or any name that contains the name OwnTracks because that would be very confusing to other users. Immagine if everone publishes his version with slight modifications to Google Play. How would a new user decide which version to use? Also, guess who would be asked for support if a third party version does not work as documented because it e.g. doesn't publish a trackerId?   

As a final word, if you decide to distribute a third party version to friends and family, please remove Fabric.io crash reporting from that build so that we don't get crash reports from your modified version and remove all support links from that build. 

I'm sorry that this probably isn't what you want to hear, but there are many oppinions on this project and we cannot pursue all proposals. 

Kind regards, 

Alexander

Hi, 

you can import a configuration by choosig the OwnTracks app from the Android open dialog. E.g. if you have the .otrc file in your Dropbox or GMail app, click the file and choose to open it with OwnTracks. A dialog will show all config keys and values that will be imported. You can even include the mode to which the config will apply and which will be activated after importing the config, so you don't even need to specify private mode before importing it. 

Regarding your questions: 
1) You said you were confused that deviceID and clientId were different things. Let me say that you were not alone with this. This is *exactly* why we removed it from the interface. The clientId is a MQTT specific thing that normally doesn't need to be set to a specific value and with the MQTT 3.1.1 specification can even be ommited entirely. Regarding the device topic, we had many support requests because people changed it and wondered why their reported locations didn't occur on other devices because they didn't know what they were doing. Thus we opted to remove it in newer versions and make it configurable via config import for advanced users. 

Could you specify a usecase why you need to regularly view the clientId and device topic in the app? I believe it's something you configure once and then forget about it. 

Moreover, private mode refers to using OwnTracks with the infrastructure of your choice. This is explained in great detail in the documentation. This can be private infrastructure or a public third party public infrastructure, so the name **might** me confusing. How would you name the mode then? 

2) The imported config doesn't need to include your password. If you export the config, you can choose to not include any credentials and just export common config values. Alternatively, if you have an existing config, you can edit the file and just remove the parameter. If some config keys are not included in the config, the import of that key is just skipped and the configured value is not changed so no one forces you to export your password in clear text. You can thus just distribute a config without password and meet in a tap-proof room in person do distribute passwords. 

3) This is exactly why you cannot configure it in the interface like explained above. 

4) Why would you need to do that?

5) Yes, and it's also sending **radius**, **tst** and much more that you might not need. We cannot make everything configurable. 

Sorry for the harsh words, but the provided pull request does not make it easier to configure but instead provides an additional mode that is completely redundant and will most probably confuse everyone besides you. 

You are explicitly *not* chained to our backends. You are still free to configure all important parameters. User relevant parameters can be configured the the app while advanced features can be set through the imported config. 

Also, removing options form the visible interface of the app was a conscious decision because there were many features that are seldomly needed because we provide sane defaults and that were configusing for 99% of regular users. 

That being said, you are of course free to maintain your own fork on Github and distribute it to your friends, family and pets as long as it adheres to the EPL license. **However**, do not distribute it to Google Play under the name OwnTracks or any name that contains the name OwnTracks because that would be very confusing to other users. Immagine if everone publishes his version with slight modifications to Google Play. How would a new user decide which version to use? Also, guess who would be asked for support if a third party version does not work as documented because it e.g. doesn't publish a trackerId?   

As a final word, if you decide to distribute a third party version to friends and family, please remove Fabric.io crash reporting from that build so that we don't get crash reports from your modified version and remove all support links from that build. 

I'm sorry that this probably isn't what you want to hear, but there are many oppinions on this project and we cannot pursue all proposals. 

Kind regards, 

Alexander

**Comment by tmylk** [comment]
Thank you for the explanation! It is clear to me now.
 I totally agree that UI has to be simple to use for this app to be popular. 
I will try out the import function later but it seems that it already does what is needed here.

**Pull request closed without merging**
