### PR TITLE
Start implementing graceful fail/override on unavailable Google Play Services

### PR DESCRIPTION
**Pull request by friesenkiwi**
So, as discussed earlier (#82, #84, #88, #224, #239, #379, #397), I started implementing a graceful fail/override/fallback.
The behavior of the app should be unchanged on devices with Google Play Services available. But if they are not, the user is offered an option to enter "unsupported override mode". This can be also later switched off and on in the preferences under "Misc".

The only actual feature working in this mode currently is connecting to a MQTT server and opening the "Friends" list. But there will be no reporting of own position or displaying of map or such. That would be subject to future PRs.

I strove to introduce as little additional complexity as I could, also I designed the GoogleApiAvailabilityWrapper to resemble the original GoogleApiAvailability as close as possible.
I hope, it is OK this way, what do you say?

The play-services-base dependency seems to be unused anyway.

Also, the PR contains a couple more extracted strings and translations.

I added a runnable debug APK in my F-Droid-Repo at http://fdroid.denk-nach-mcfly.de/, if anyone would like to test it.

### CODE REVIEW

**Comment by binarybucks** [comment]
Very good 👍

Two minor things:
Please change logging from Log.x(TAG,...) to Timber.x(...)? In your added files. It automatically sets a correct TAG and logs the method name. I'll replace occurrences in existing files when I touch them. 

Please add import and export annotations to the new preferences methods (all modes). I think that key should be contained in exportable configs, what do you think?

**Comment by friesenkiwi** [comment]
Glad you like it :-) And thank you for your comments, I wasn't aware of Timber and the Ex-/Import Annotations yet.

- Changed the Logging in all touched files
- Added Import/Export

Actually I thought it would be reasonable to save the PLAY_OVERRIDE key to the sharedPreferences instead of the mode Preferences, but I couldn't find a way to "set" a preferences file for a specific preference in ActivityPreferences.java?

Also, the linter asks about replacing commit() by apply():

>  Consider using apply() instead; commit writes its data to persistent storage immediately, whereas apply will handle it in the background

Is there any reason not to do?

**Comment by binarybucks** [comment]
There was no real use for mode free settings until now besides some special keys (first start, mode), so there's no interface for that.

I'd say you leave it as it is and store it mode specific. 

The reason commit instead of apply is used because apply completed in the background and reads after a write might return the wrong value. We could test if it works when using apply instead.

**Comment by friesenkiwi** [comment]
OK, so I didn't miss something on the preferences. So we leave it as it is.

Yeah, we could try to test it, I wouldn't  suspect there to be many problems since the linter suggests it so openly, but there is no real "need" for it either (apart from getting rid of some yellowish marks ;-)

**Comment by friesenkiwi** [comment]
I worked on it a little more. Now not only the WelcomeActivity is using the transparent wrapper, but the ActivityStatus and ServiceApplication as well. This way, there's less failed attempts and less logging events, also WelcomeActivity is even less entangled to the GoogleApiAvailability.

I'd say, it would be ready to merge now, what do you say?

My next step could be to try to propose an alternative ActivityMap implementation, based on osmdroid, which could be automatically used on overrideMode.

**Comment by friesenkiwi** [comment]
Actually, I switched plans and started to again replace Google's GeofencingApi by the one provided by LOST, because the missing Geofencing feature is currently being implemented (https://github.com/mapzen/LOST/pull/88). There is a working app (with the application id changed to org.owntracks.beta) in my F-Droid repo (https://fdroid.denk-nach-mcfly.de/, direct apk link: https://fdroid.denk-nach-mcfly.de/fdroid/repo/owntracks--beta-1.1.1.2-11103.apk), made a different branch for now (friesenkiwi/android@5c6429ce87e7a53dcfadeacb6c9dbe5bc38b0475) to not crowd this PR, also there is not yet a switchable choice to use Google or LOST.

**Comment by binarybucks** [comment]
@friesenkiwi Could you walk me through the flow how the GoogleApiAvailability and GoogleApiAvailabilityWrapper work together? 
Why are the constants from the original Google API duplicated, can we not reuse the? 
I was under the impression that the GoogleApiAvailability class is compiled with the APK and thus always available, even when Play Services are not installed.  

I see that is is working, but not really why ;)

**Comment by jpmens** [comment]
@binarybucks & @friesenkiwi : if you guys want to "chat", I can invite you
to our semi-publiic Slack Team. In that case, @friesenkiwi, I'd need your
e-mail address; please send it to support@owntracks.org

**Comment by friesenkiwi** [comment]
@binarybucks Hey, thank you for merging and the new developments, I already rebased my other fork to replace Google's `FusedLocationAPI` by LOST. It is working, even with Geofences :), since I helped with including this as a new feature in the latest developments. These are not finished yet though. But would you like to test it? I'd provide you an apk?

Well yes, at the moment the original proprietary `GoogleApiAvailability` is compiled in and thus the constants would be available. But my idea was to make it possible, e.g. by a Gradle compile variant, to later remove the Google dependency as a whole, so the App may be called "FLOSS" and may be included in F-Droid. There are already other examples of a slightly altered version of an app in the repository, so it wouldn't be the first time. It seems, there could be a decently big group of people interested in just that, even possibly ready to sacrifice some functionality (like HTTP etc.).

`wrapper.GoogleApiAvailability` is a basic drop in replacement implementation, providing kind of "static" responses to the API calls, but also adding an "override" functionality. Additionally, there is an extended `GoogleApiAvailabilityWrapper` class, which wraps (hence the name ;-)) an instance of the `gms.common.GoogleApiAvailability` and passes on the API calls and responses. The base class also acts as a gate, and when calling it's `getInstance()` method, it will usually return not an instance of itself, but of the `GoogleApiAvailabilityWrapper` extension class. This will happen even on my device, where the PlayServices are not installed, as long as the `gms.common.GoogleApiAvailability` binary is compiled in. But if this returns the SERVICE_MISSING, SERVICE_INVALID or API_UNAVAILABLE error codes, it will show the dialog from the base class to set the override in the app.
This way, the app itself can use the `wrapper.GoogleApiAvailability` nearly exactly like the propietary one, with only a couple of small additions for the override (like implementing the `GoogleApiAvailabilityResponder` interface, which you had kind of designed before already). Also, there will be no error or warning in the logs.

My idea was, to use the override setting in the app to later also determine, which `FusedLocationAPI` (Google/LOST) and Maps (Google/Osmdroid) implementation to use. With LOST, as I said, it is already working as replacement, but not switchable yet. Osmdroid I didn't work on yet, there's only so much time... ;-)

Humm ... did I describe it understandably? Or are there things missing?

@jpmens Yeah... I'm a little uncomfortable and not yet convinced of Slack... was hoping to dodge that bullet by XMPP, Mumble or Mattermost but didn't manage to setup a server yet (time, you know... ;-))
Sorry, I'm a little arduous for that matters...
But I see it might be helpful... so just give me some more time.
If you like, we could even meet for a hack-weekend or so, since, I belive we don't live too far away from each others? (I'm from the Ruhrgebiet). Or maybe on the 33C3 in Hamburg?

**Comment by Azimoth** [comment]
I wanted to give "owntracks without Google Play Services" a try but I cannot find owntracks on f-droid (neither with or without denk-nach-mcfly added to the repositories) nor did the direct link above work, when I clicked it.
Is there still a way to get a google-services-free version of Owntracks? Or did you stop working on it?

**Comment by friesenkiwi** [comment]
Unfortunately, while I still would want to work on that very much, I can't currently find the time for it, especially not when working alone. :-( But the graceful fail/override is merged to the app and works. I removed the .apk from my repo when it was merged to the official app and released there.

**Comment by friesenkiwi** [comment]
The app will be able to receive data, but not to send or display it on the map. This can actually already be quite helpful, to just see it in the list. Those are two functionalities which should be fairly easy to implement (actually I had a version with sending data via LOST some time ago), but I can't do it on my own. I need someone to team up with.
I don't know any other app but on F-Droid I saw a couple of, promising to be able to do it, though I never tested one and am a bit sceptic that any of them work as reliable as OwnTracks does.

**Comment by binarybucks** [comment]
The override has been removed and OwnTracks is not available on F-Droid.

**Comment by friesenkiwi** [comment]
Sorry to hear that :-(

**Comment by nycex** [comment]
May I ask why this was removed?

**Pull request merged**
